# Tesserae Studio installer, Windows / PowerShell.
#
# Usage (in PowerShell):
#   iwr https://raw.githubusercontent.com/dmellok/tesserae-studio/main/install.ps1 -UseBasicParsing | iex
#
# Optional env vars (pre-answer the prompts):
#   $env:STUDIO_DIR           default: $HOME\tesserae-studio
#   $env:STUDIO_PORT          default: 8770 (otherwise prompted)
#   $env:STUDIO_TESSERAE_URL  live Tesserae for data + faithful render
#   $env:PYTHON               default: python
#   $env:NONINTERACTIVE = '1' skip prompts, use defaults

$ErrorActionPreference = 'Stop'

function Step($msg)  { Write-Host ""; Write-Host "== $msg ==" -ForegroundColor White }
function Info($msg)  { Write-Host "  $msg" -ForegroundColor DarkGray }
function Ok($msg)    { Write-Host "[OK] $msg" -ForegroundColor Green }
function Warn($msg)  { Write-Host "[!] $msg"  -ForegroundColor Yellow }
function Fail($msg)  { Write-Host "[X] $msg"  -ForegroundColor Red; exit 1 }

$InstallDir  = if ($env:STUDIO_DIR) { $env:STUDIO_DIR } else { Join-Path $HOME 'tesserae-studio' }
$RepoUrl     = if ($env:STUDIO_REPO) { $env:STUDIO_REPO } else { 'https://github.com/dmellok/tesserae-studio.git' }
$Branch      = if ($env:STUDIO_BRANCH) { $env:STUDIO_BRANCH } else { 'main' }
$Python      = if ($env:PYTHON) { $env:PYTHON } else { 'python' }
$Port        = $env:STUDIO_PORT
$TesseraeUrl = $env:STUDIO_TESSERAE_URL
$NonInter    = $env:NONINTERACTIVE -eq '1'

function Prompt-Default([string]$question, [string]$default) {
  if ($NonInter) { return $default }
  $answer = Read-Host "$question [$default]"
  if ([string]::IsNullOrWhiteSpace($answer)) { return $default }
  return $answer
}

# ---------- sanity ----------
Step "Sanity checks"
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
  Fail "git not found. Install Git for Windows first: https://git-scm.com/"
}
if (-not (Get-Command $Python -ErrorAction SilentlyContinue)) {
  Fail "$Python not found. Install Python 3.11+ from https://www.python.org/ (tick 'Add to PATH')."
}
if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
  Fail "node not found. Install Node 18+ from https://nodejs.org/."
}
$pyVer = & $Python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')"
$major, $minor = $pyVer.Split('.') | ForEach-Object { [int]$_ }
if ($major -lt 3 -or ($major -eq 3 -and $minor -lt 11)) {
  Fail "Python 3.11+ required (found $pyVer)."
}
$nodeMajor = [int]((node -p "process.versions.node.split('.')[0]"))
if ($nodeMajor -lt 18) { Fail "Node 18+ required (found $(node -v))." }
Ok "git + $Python ($pyVer) + node $(node -v)"

# ---------- prompts ----------
if (-not $Port) { $Port = Prompt-Default "Serve Studio on which port?" "8770" }
$Port = ($Port -replace '[^0-9]', '')
if (-not $Port -or [int]$Port -lt 1 -or [int]$Port -gt 65535) { Warn "Invalid port, using 8770"; $Port = '8770' }
if (-not $TesseraeUrl) {
  $TesseraeUrl = Prompt-Default "Live Tesserae URL (blank for standalone)" "http://localhost:8765"
}
Info "Port: $Port"; Info "Tesserae: $TesseraeUrl"

# ---------- clone / update ----------
Step "Source"
if (Test-Path (Join-Path $InstallDir '.git')) {
  Info "Existing checkout, pulling $Branch"
  git -C $InstallDir fetch --quiet origin $Branch
  git -C $InstallDir checkout --quiet $Branch
  git -C $InstallDir pull --quiet --ff-only origin $Branch
} elseif (Test-Path $InstallDir) {
  Fail "$InstallDir exists but isn't a git checkout. Move or delete it, then re-run."
} else {
  Info "Cloning $RepoUrl -> $InstallDir"
  git clone --quiet --branch $Branch $RepoUrl $InstallDir
}
Set-Location $InstallDir
Ok "Source ready"

# ---------- backend ----------
Step "Backend (Python)"
if (-not (Test-Path 'server\.venv')) { Info "Creating server\.venv"; & $Python -m venv server\.venv }
& server\.venv\Scripts\python.exe -m pip install --quiet --upgrade pip
& server\.venv\Scripts\python.exe -m pip install --quiet -e .\server
Ok "Backend installed"

# ---------- front end ----------
Step "Front end (Node)"
Info "Installing + building web\ (this can take a minute)"
Push-Location web
npm ci --silent
npm run build --silent
Pop-Location
Ok "Front end built to web\dist"

# ---------- launcher ----------
$run = @"
# Auto-generated by install.ps1. Edit freely.
Set-Location `$PSScriptRoot
if (-not `$env:STUDIO_PORT) { `$env:STUDIO_PORT = '$Port' }
if (-not `$env:STUDIO_HOST) { `$env:STUDIO_HOST = '127.0.0.1' }
if (-not `$env:STUDIO_TESSERAE_URL) { `$env:STUDIO_TESSERAE_URL = '$TesseraeUrl' }
& server\.venv\Scripts\python.exe -m uvicorn studio_server.app:app --app-dir server --host `$env:STUDIO_HOST --port `$env:STUDIO_PORT
"@
Set-Content -Path 'run.ps1' -Value $run -Encoding UTF8

# ---------- done ----------
Step "Done"
Write-Host "Tesserae Studio is installed at $InstallDir" -ForegroundColor White
Write-Host ""
Write-Host "Start it:"
Write-Host "  cd $InstallDir"
Write-Host "  .\run.ps1"
Write-Host ""
Write-Host "Then visit http://localhost:$Port/" -ForegroundColor White
