// Generate lint-clean client.js from the layout model, and parse the model back
// out (round-trip). Output paints from Spectra tokens, sizes with cqmin (the
// root sets container-type: size), sets shadow.innerHTML once, uses ph-bold
// icons, and never fetches or hard-codes hex.
//
// Each node compiles to a JS *expression* that evaluates to an HTML string:
// static HTML as single-quoted string literals, data bindings as `+ e(g("p")) +`.

import type { Align, IconNode, Justify, LayoutNode, Layout, StackNode, StatNode, TextNode } from "./model";

const MARKER = "@tesserae-studio:layout";

const ALIGN_CSS: Record<Align, string> = {
  start: "flex-start", center: "center", end: "flex-end", stretch: "stretch",
};
const JUSTIFY_CSS: Record<Justify, string> = {
  start: "flex-start", center: "center", end: "flex-end", between: "space-between",
};

/** HTML-escape text content. */
function esc(s: string): string {
  return s.replace(/[&<>]/g, (c) => `&#${c.charCodeAt(0)};`);
}

/** A single-quoted JS string literal of the given (already HTML-safe) text. */
function jsStr(s: string): string {
  return "'" + s.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\n/g, "\\n") + "'";
}

/** Only allow phosphor icon class chars so codegen can't inject markup. */
function safeIcon(icon: string): string {
  const cleaned = (icon || "").trim().replace(/[^a-z0-9- ]/g, "");
  return cleaned || "ph-square";
}

function stackStyle(s: StackNode, isRoot: boolean): string {
  return [
    "display:flex",
    `flex-direction:${s.dir === "row" ? "row" : "column"}`,
    s.gap ? `gap:${s.gap}cqmin` : "",
    s.padding ? `padding:${s.padding}cqmin` : "",
    `align-items:${ALIGN_CSS[s.align]}`,
    `justify-content:${JUSTIFY_CSS[s.justify]}`,
    s.bg !== "none" ? `background:var(${s.bg})` : "",
    s.bg !== "none" && !isRoot ? "border-radius:4cqmin" : "",
    isRoot ? "width:100%;height:100%" : s.grow ? "flex:1" : "",
  ]
    .filter(Boolean)
    .join(";");
}

/** Compile a node to a JS expression string (evaluates to an HTML string). */
function nodeExpr(node: LayoutNode, isRoot: boolean): string {
  switch (node.type) {
    case "stack": {
      const open = `<div style="${stackStyle(node, isRoot)}">`;
      const close = `</div>`;
      if (!node.children.length) return jsStr(open + close);
      return [jsStr(open), ...node.children.map((c) => nodeExpr(c, false)), jsStr(close)].join(" + ");
    }
    case "text": {
      const t = node as TextNode;
      const style = `font-size:${t.size}cqmin;font-weight:${t.weight};color:var(${t.color});text-align:${t.align}`;
      const open = `<div style="${style}">`;
      if (t.bind) return [jsStr(open), `e(g(${JSON.stringify(t.bind)}))`, jsStr("</div>")].join(" + ");
      return jsStr(open + esc(t.content) + "</div>");
    }
    case "stat": {
      const s = node as StatNode;
      const style = `font-size:${s.size}cqmin;font-weight:700;line-height:1;color:var(${s.color});font-variant-numeric:tabular-nums`;
      const open = `<div style="${style}">`;
      const unit = s.unit
        ? `<span style="font-size:0.42em;color:var(--text-muted)"> ${esc(s.unit)}</span>`
        : "";
      const close = unit + "</div>";
      if (s.bind) return [jsStr(open), `e(g(${JSON.stringify(s.bind)}))`, jsStr(close)].join(" + ");
      return jsStr(open + esc(s.content) + close);
    }
    case "icon": {
      const i = node as IconNode;
      const style = `font-size:${i.size}cqmin;color:var(${i.color});line-height:1`;
      return jsStr(`<i class="ph-bold ${safeIcon(i.icon)}" style="${style}"></i>`);
    }
  }
}

export function generateClientJs(layout: Layout): string {
  const usesIcons = JSON.stringify(layout).includes('"type":"icon"');
  const frags = Object.entries(layout.fragments)
    .map(([id, root]) => `    ${JSON.stringify(id)}: () => ${nodeExpr(root, true)},`)
    .join("\n");
  const phosphor = usesIcons
    ? '<link rel="stylesheet" href="/static/icons/phosphor/bold/style.css">'
    : "";
  const model = "\n\n/* " + MARKER + "\n" + JSON.stringify(layout, null, 2) + "\n*/\n";
  return (
    "// Generated by Tesserae Studio's visual editor. Edit in Design mode; the\n" +
    "// model below round-trips. Paints from Spectra tokens, sizes with cqmin.\n" +
    "export default function (shadow, ctx) {\n" +
    "  const data = ctx.data || {};\n" +
    "  const g = (p) => p.split(/[.[\\]]+/).filter(Boolean).reduce((o, k) => (o == null ? o : o[k]), data);\n" +
    '  const e = (v) => String(v == null ? "" : v).replace(/[&<>]/g, (c) => "&#" + c.charCodeAt(0) + ";");\n' +
    '  const fragment = (ctx.cell && ctx.cell.fragment) || "full";\n' +
    "  const F = {\n" + frags + "\n  };\n" +
    "  const body = (F[fragment] || F.full || Object.values(F)[0] || (() => \"\"))();\n" +
    "  shadow.innerHTML =\n" +
    `    '<link rel="stylesheet" href="/static/style/spectra-widgets.css">${phosphor}' +\n` +
    `    '<div class="w" style="box-sizing:border-box;width:100%;height:100%;container-type:size;' +\n` +
    "    'background:var(--surface);color:var(--text-primary)\">' + body + '</div>';\n" +
    "}\n" +
    model
  );
}

/** Extract the embedded layout model from generated client.js, or null. */
export function parseLayout(clientJs: string): Layout | null {
  const start = clientJs.indexOf(MARKER);
  if (start < 0) return null;
  const open = clientJs.indexOf("\n", start);
  const end = clientJs.indexOf("*/", open);
  if (open < 0 || end < 0) return null;
  try {
    const parsed = JSON.parse(clientJs.slice(open + 1, end).trim());
    if (parsed && parsed.version === 1 && parsed.fragments) return parsed as Layout;
  } catch {
    return null;
  }
  return null;
}

export function isVisualWidget(clientJs: string): boolean {
  return clientJs.includes(MARKER);
}
